version: '2'
services:
  empower-db:
    extends:
      file: ./mariadb.yml
      service: empower-db
    networks:
      hr_net:
        ipv4_address: 172.10.20.2


  empower-app:
#    image: redcopy/springmongoresttest:latest
    image: redcopy/empower-hr:latest
    container_name: empower-hr-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.10.20.2:3306/empoweringhr?useSSL=false
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_USERNAME=empower
      - SPRING_DATASOURCE_PASSWORD=test123

      - SPRING_MYSQL_JDBC_URL=jdbc:mysql://172.10.20.2:3306/empoweringhr?useSSL=false&user=empower&password=test123"
      - SPRING_MYSQL_USER=empower
      - SPRING_MYSQL_PASS=test123
      - HIBERNATE_DIALECT=org.hibernate.dialect.MariaDB10Dialect
      - SPRING_JPA_GENERATE_DDL=true
      - EMPOW_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8082:8080

    networks:
      hr_net:
        ipv4_address: 172.10.20.5



networks:
  hr_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.10.20.0/24
          gateway: 172.10.20.1


