version: '2'
services:
    empower-db:
        container_name: empower-db
        image: mariadb:latest

        environment:
            #            - MYSQL_HOST: localhost
            - MYSQL_USER=empower
            - MYSQL_ROOT_PASSWORD=test123
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=empoweringhr
            - SPRING_MYSQL_JDBC_URL=jdbc:mysql://172.10.20.2:3306/empoweringhr?useUnicode=true&characterEncoding=utf8&useSSL=false


        volumes:
            - "./volumes/init/init.sql:/usr/local/bin/mysql_init.sql"
            - "./volumes/init/seed.sql:/docker-entrypoint-initdb.d/dump.sql"
        ports:
        - 3306:3306

#   docker run -d --name empower-mysql --network empowering-netwrk  --ip 192.168.99.108 -e MYSQL_ROOT_PASSWORD=test123 -p 3306:3306 -v  EmpoweringHR/src/main/docker/init.sql:/docker-entrypoint-initdb.d/init.sql mysql:latest




